# Generated by Django 3.1.3 on 2020-12-14 11:09

import collection_settings.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection_name', models.CharField(blank=True, default='', max_length=174, verbose_name='コレクション名')),
                ('institution_code', models.CharField(blank=True, default='', max_length=10, verbose_name='機関コード')),
                ('latest_collection_code', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999999999999)], verbose_name='標本IDの最終番号')),
                ('note', models.TextField(blank=True, default='', max_length=200, verbose_name='備考')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_settings', to=settings.AUTH_USER_MODEL, verbose_name='ユーザーモデル')),
            ],
            options={
                'db_table': 'collection_settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
