# Generated by Django 3.1.3 on 2020-11-06 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UesrProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contient', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='大陸')),
                ('island_group', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='島郡')),
                ('island', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='島')),
                ('country', models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='国名コード(2文字 ISO 3166-1)')),
                ('state_provice', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='県(州)')),
                ('institution_code', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='機関コード')),
                ('collection_code', models.IntegerField(blank=True, default=0, null=True, verbose_name='標本ID')),
                ('identified_by', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='同定者')),
                ('collecter', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='採集者')),
                ('preparation_type', models.CharField(blank=True, default='dry specimens', max_length=20, null=True, verbose_name='標本の種類')),
                ('disposition', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='現在の標本の状況')),
                ('lifestage', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='ライフステージ')),
                ('establishment_means', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='生成プロセス')),
                ('rights', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='ライセンス')),
                ('kingdom', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='界')),
                ('phylum', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='門')),
                ('class_name', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='鋼')),
                ('order', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='目')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
