# Generated by Django 3.1.3 on 2020-12-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='collection_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='institution_code',
        ),
    ]
