# Generated by Django 3.1.3 on 2020-11-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uesrprofile',
            name='class_name',
            field=models.CharField(blank=True, default='Insecta', max_length=30, null=True, verbose_name='鋼'),
        ),
        migrations.AlterField(
            model_name='uesrprofile',
            name='kingdom',
            field=models.CharField(blank=True, default='Animalia', max_length=30, null=True, verbose_name='界'),
        ),
        migrations.AlterField(
            model_name='uesrprofile',
            name='phylum',
            field=models.CharField(blank=True, default='Arthropoda', max_length=30, null=True, verbose_name='門'),
        ),
    ]
