# Generated by Django 3.1.3 on 2020-11-14 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import my_utils.file_tools
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxa', '0001_initial'),
        ('collect_points', '0003_auto_20201106_1840'),
        ('tours', '0002_auto_20201106_1730'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_last_modified', models.DateTimeField(auto_now_add=True, verbose_name='最終更新日時')),
                ('collection_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='コレクション名')),
                ('institution_code', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='機関コード')),
                ('collection_code', models.IntegerField(blank=True, default=0, null=True, verbose_name='標本ID')),
                ('identified_by', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='同定者')),
                ('date_identified', models.DateTimeField(blank=True, null=True, verbose_name='同定年月日')),
                ('collecter', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='採集者')),
                ('year', models.IntegerField(blank=True, default=0, null=True, verbose_name='採集年')),
                ('month', models.IntegerField(blank=True, default=0, null=True, verbose_name='採集月')),
                ('day', models.IntegerField(blank=True, default=0, null=True, verbose_name='採集日')),
                ('sex', models.CharField(blank=True, default='U', max_length=1, null=True, verbose_name='性別')),
                ('preparation_type', models.CharField(blank=True, default='dry specimens', max_length=20, null=True, verbose_name='標本の種類')),
                ('disposition', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='現在の標本の状況')),
                ('sampling_protocol', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='採集方法')),
                ('sampling_effort', models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='採集中の作業メモ')),
                ('lifestage', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='ライフステージ')),
                ('establishment_means', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='生成プロセス')),
                ('rights', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='ライセンス')),
                ('note', models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='備考')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=my_utils.file_tools.user_portfolio_directory_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=my_utils.file_tools.user_portfolio_directory_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=my_utils.file_tools.user_portfolio_directory_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=my_utils.file_tools.user_portfolio_directory_path)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=my_utils.file_tools.user_portfolio_directory_path)),
                ('collect_point_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collect_points.collectpoint', verbose_name='採集地点情報')),
                ('custom_taxon_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_taxon_info', to='taxa.customtaxon', verbose_name='カスタム分類情報')),
                ('default_taxon_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_taxon_info', to='taxa.defaulttaxon', verbose_name='デフォルト分類情報')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.tour', verbose_name='採集行')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'specimens',
                'ordering': ['-date_last_modified'],
            },
        ),
    ]
