# Generated by Django 3.1.3 on 2020-11-14 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0001_initial'),
        ('specimens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='custom_taxon_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_taxa', to='taxa.customtaxon', verbose_name='カスタム分類情報'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='default_taxon_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_taxa', to='taxa.defaulttaxon', verbose_name='デフォルト分類情報'),
        ),
    ]
