# Generated by Django 3.1.3 on 2021-06-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0002_auto_20210318_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='allow_kojin_shuzo',
            field=models.BooleanField(blank=True, default=False, verbose_name='個人収蔵.com様への投稿の可否'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='published_kojin_shuzo',
            field=models.BooleanField(blank=True, default=False, verbose_name='個人収蔵.com様へ投稿済みか?'),
        ),
    ]
