# Generated by Django 3.1.3 on 2020-11-07 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0003_remove_specimen_taxon_info'),
        ('taxa', '0003_auto_20201107_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='custom_taxon_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxa.customtaxon', verbose_name='カスタム分類情報'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='default_taxon_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxa.defaulttaxon', verbose_name='デフォルト分類情報'),
        ),
    ]
