# Generated by Django 3.1.3 on 2020-12-06 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0003_auto_20201116_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='date_identified',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='同定年月日'),
        ),
    ]
