# Generated by Django 3.1.3 on 2020-12-11 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0005_auto_20201206_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='collecter',
            field=models.CharField(blank=True, default='', max_length=18, verbose_name='採集者'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='collection_code',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999999999)], verbose_name='標本ID'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='collection_name',
            field=models.CharField(blank=True, default='', max_length=174, verbose_name='コレクション名'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='day',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='採集日(不明な場合0を指定)'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='identified_by',
            field=models.CharField(blank=True, default='', max_length=19, verbose_name='同定者'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='institution_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='機関コード'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='month',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='採集月(不明な場合0を指定)'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='year',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='採集年(不明な場合0を指定)'),
        ),
    ]
