# Generated by Django 3.1.3 on 2020-11-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='note',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='採集行のタイトル'),
        ),
    ]
