# Generated by Django 3.1.3 on 2020-12-06 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20201106_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='採集行終了日'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='note',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='採集行開始日'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='採集行のタイトル'),
        ),
    ]
