# Generated by Django 3.1.3 on 2020-12-14 07:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20201206_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='track',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
