# Generated by Django 3.1.3 on 2020-11-06 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import my_utils.file_tools
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kingdom', models.CharField(blank=True, max_length=30, null=True, verbose_name='界')),
                ('phylum', models.CharField(blank=True, max_length=30, null=True, verbose_name='門')),
                ('class_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='鋼')),
                ('order', models.CharField(blank=True, max_length=30, null=True, verbose_name='目')),
                ('suborder', models.CharField(blank=True, max_length=30, null=True, verbose_name='亜目')),
                ('family', models.CharField(blank=True, max_length=30, null=True, verbose_name='科')),
                ('subfamily', models.CharField(blank=True, max_length=30, null=True, verbose_name='亜科')),
                ('tribe', models.CharField(blank=True, max_length=30, null=True, verbose_name='族')),
                ('subtribe', models.CharField(blank=True, max_length=30, null=True, verbose_name='亜族')),
                ('genus', models.CharField(blank=True, max_length=30, null=True, verbose_name='属')),
                ('subgenus', models.CharField(blank=True, max_length=30, null=True, verbose_name='亜属')),
                ('species', models.CharField(blank=True, max_length=30, null=True, verbose_name='種')),
                ('subspecies', models.CharField(blank=True, max_length=30, null=True, verbose_name='亜種')),
                ('scientific_name_author', models.CharField(blank=True, max_length=50, null=True, verbose_name='記載者')),
                ('name_publishedin_year', models.IntegerField(blank=True, null=True, verbose_name='記載年')),
                ('japanese_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='和名')),
                ('distribution', models.CharField(blank=True, max_length=100, null=True, verbose_name='分布')),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='備考')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=my_utils.file_tools.user_portfolio_directory_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=my_utils.file_tools.user_portfolio_directory_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=my_utils.file_tools.user_portfolio_directory_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=my_utils.file_tools.user_portfolio_directory_path)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=my_utils.file_tools.user_portfolio_directory_path)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'taxa',
                'ordering': ['-created_at'],
            },
        ),
    ]
