# Generated by Django 3.1.3 on 2020-12-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttaxon',
            name='class_name',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, verbose_name='鋼'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='distribution',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='分布'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='family',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, verbose_name='科'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='genus',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, verbose_name='属'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='japanese_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='和名'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='kingdom',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, verbose_name='界'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='name_publishedin_year',
            field=models.IntegerField(blank=True, default=0, verbose_name='記載年'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='note',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='order',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, verbose_name='目'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='phylum',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, verbose_name='門'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='scientific_name_author',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='記載者'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='species',
            field=models.CharField(blank=True, default='sp.', max_length=30, verbose_name='種'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='subfamily',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, verbose_name='亜科'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='subgenus',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, verbose_name='亜属'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='suborder',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, verbose_name='亜目'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='subspecies',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='亜種'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='subtribe',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, verbose_name='亜族'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='tribe',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, verbose_name='族'),
        ),
    ]
