# Generated by Django 3.1.3 on 2021-01-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='species',
            field=models.CharField(blank=True, default='sp', max_length=30, verbose_name='種'),
        ),
    ]
