# Generated by Django 3.1.3 on 2021-02-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0002_auto_20210130_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='distribution',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='分布'),
        ),
    ]
