# Generated by Django 3.1.3 on 2020-11-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0003_auto_20201107_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttaxon',
            name='class_name',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, null=True, verbose_name='鋼'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='family',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, null=True, verbose_name='科'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='genus',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, null=True, verbose_name='属'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='kingdom',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, null=True, verbose_name='界'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='order',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, null=True, verbose_name='目'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='phylum',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, null=True, verbose_name='門'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='species',
            field=models.CharField(blank=True, default='sp.', max_length=30, null=True, verbose_name='種'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='subfamily',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, null=True, verbose_name='亜科'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='subgenus',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, null=True, verbose_name='亜属'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='suborder',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, null=True, verbose_name='亜目'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='subtribe',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, null=True, verbose_name='亜族'),
        ),
        migrations.AlterField(
            model_name='defaulttaxon',
            name='tribe',
            field=models.CharField(blank=True, default='Unidentified', max_length=30, null=True, verbose_name='族'),
        ),
    ]
