# Generated by Django 3.1.3 on 2021-02-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0003_auto_20210224_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='distribution',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='分布'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='note',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='備考'),
        ),
    ]
