# Generated by Django 3.1.3 on 2021-03-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0005_auto_20210224_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='subfamily',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='亜科'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='subgenus',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='亜属'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='suborder',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='亜目'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='subtribe',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='亜族'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='tribe',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='族'),
        ),
    ]
