# Generated by Django 3.1.3 on 2021-03-07 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0006_auto_20210306_0830'),
        ('taxa', '0006_auto_20210301_1905'),
    ]

    operations = [
    ]
