# Generated by Django 3.1.3 on 2021-06-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0007_merge_20210307_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='change_genus_brackets',
            field=models.BooleanField(blank=True, default=False, verbose_name='属移動カッコの有無'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='unknown_author_brackets',
            field=models.BooleanField(blank=True, default=False, verbose_name='記載者不明角カッコの有無'),
        ),
    ]
