# Generated by Django 3.1.3 on 2021-06-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0008_auto_20210607_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='unknown_name_publishedin_year_brackets',
            field=models.BooleanField(blank=True, default=False, verbose_name='記載年不明角カッコの有無'),
        ),
    ]
