# Generated by Django 3.1.3 on 2021-06-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0009_taxon_unknown_name_publishedin_year_brackets'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='actual_dist_year',
            field=models.IntegerField(blank=True, default=0, verbose_name='記載実流通年'),
        ),
    ]
