# Generated by Django 3.1.3 on 2020-12-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0006_auto_20201211_1812'),
        ('label_maker', '0003_auto_20201213_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimenlabel',
            name='label_specimens',
            field=models.ManyToManyField(blank=True, related_name='label_specimens', to='specimens.Specimen', verbose_name='標本データ'),
        ),
    ]
