# Generated by Django 3.1.3 on 2020-11-06 03:44

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import my_utils.file_tools
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contient', models.CharField(blank=True, max_length=20, null=True, verbose_name='大陸')),
                ('island_group', models.CharField(blank=True, max_length=50, null=True, verbose_name='島郡')),
                ('island', models.CharField(blank=True, max_length=50, null=True, verbose_name='島')),
                ('country', models.CharField(blank=True, max_length=2, null=True, verbose_name='国名コード(2文字 ISO 3166-1)')),
                ('state_provice', models.CharField(blank=True, max_length=50, null=True, verbose_name='県(州)')),
                ('county', models.CharField(blank=True, max_length=50, null=True, verbose_name='海外における郡・区(市より上の単位)')),
                ('municipality', models.CharField(blank=True, max_length=50, null=True, verbose_name='市名以下の詳細地名')),
                ('verbatim_locality', models.TextField(blank=True, null=True, verbose_name='採集地の説明')),
                ('japanese_place_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='日本語地名')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9, null=True, verbose_name='経度')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9, null=True, verbose_name='緯度')),
                ('coordinate_precision', models.FloatField(blank=True, null=True, verbose_name='採集地の範囲')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('minimum_elevation', models.FloatField(blank=True, null=True, verbose_name='採集地の最低海抜距離')),
                ('maximum_elevation', models.FloatField(blank=True, null=True, verbose_name='採集地の最高海抜距離')),
                ('minimum_depth', models.FloatField(blank=True, null=True, verbose_name='採集地の水面からの最浅の距離')),
                ('maximum_depth', models.FloatField(blank=True, null=True, verbose_name='採集地の水面からの最深の距離')),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='備考')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=my_utils.file_tools.user_portfolio_directory_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=my_utils.file_tools.user_portfolio_directory_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=my_utils.file_tools.user_portfolio_directory_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=my_utils.file_tools.user_portfolio_directory_path)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=my_utils.file_tools.user_portfolio_directory_path)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collect_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collect_points',
                'ordering': ['-created_at'],
            },
        ),
    ]
