# Generated by Django 3.1.3 on 2020-11-06 09:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect_points', '0002_auto_20201106_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectpoint',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
