# Generated by Django 3.1.3 on 2020-12-09 00:42

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collect_points', '0004_auto_20201206_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectpoint',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='collectpoint',
            name='longitude',
        ),
        migrations.AddField(
            model_name='collectpoint',
            name='japanese_place_name_detail',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='日本語地名(詳細)'),
        ),
        migrations.AddField(
            model_name='collectpoint',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='collectpoint',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2, verbose_name='国名コード(2文字 ISO 3166-1)'),
        ),
        migrations.AlterField(
            model_name='collectpoint',
            name='county',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='海外における郡・区(市より上の単位)'),
        ),
        migrations.AlterField(
            model_name='collectpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='collectpoint',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='プライマリキー(UUID)'),
        ),
        migrations.AlterField(
            model_name='collectpoint',
            name='island',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='島'),
        ),
        migrations.AlterField(
            model_name='collectpoint',
            name='island_group',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='島郡'),
        ),
        migrations.AlterField(
            model_name='collectpoint',
            name='japanese_place_name',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='日本語地名(ラベル用・最小限)'),
        ),
        migrations.AlterField(
            model_name='collectpoint',
            name='municipality',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='市名以下の詳細地名(カンマ+半角スペースで区切る)'),
        ),
        migrations.AlterField(
            model_name='collectpoint',
            name='state_provice',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='県(州)'),
        ),
        migrations.AlterField(
            model_name='collectpoint',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collect_points', to=settings.AUTH_USER_MODEL, verbose_name='ユーザーモデル'),
        ),
        migrations.AlterField(
            model_name='collectpoint',
            name='verbatim_locality',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='採集地の説明'),
        ),
    ]
