# Generated by Django 3.1.3 on 2020-12-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_points', '0005_auto_20201209_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectpoint',
            name='state_provice',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='県(州)'),
        ),
    ]
