# Generated by Django 3.1.3 on 2020-12-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20201206_1522'),
        ('collect_points', '0007_collectpoint_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectpoint',
            name='tour',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tours.Tour', verbose_name='所属する採集行'),
        ),
    ]
